title: Rishab Shyamal - Your next VP of Leadership 
description: Your Wingman as We Fly and Go the Extra!
owner_name: Rishab Shyamal
github_username: RishbubS6 
github_repo: "VPofLeadership" 
baseurl: "/VPofLeadership" 
future: true
incremental: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache